stages:
  data_injestion:
    cmd: python src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    outs:
    - data/interim/
  feature_eng:
    cmd: python src/features/feature_eng.py
    deps:
    - data/interim/
    - src/features/feature_eng.py
    outs:
    - data/processed/
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed/
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
